### ISSUE TITLE
Lab 4 - Tuesday late morning

### ISSUE THREAD

**Issue by mehajain13** [OscarFHC/EAS538_2018#18]
Hey @OscarFHC and @arthur-e - it's taking me a while to update this week's lab so I won't have it done by tomorrow. I'll upload it here by Tuesday late morning. Thanks for understanding!

m

**Comment by mehajain13** [comment]
Hey @arthur-e and @OscarFHC. I've added the updated lab for this week to the repository. Since I changed the lab a ton, I created a new file called 'NRE538_week4_ttest_new.Rmd.' I really tried to make students understand what was going on behind the black box output of a t test and how they themselves could calculate the same results manually. Please let me know if you think anything is confusing!

**Comment by OscarFHC** [comment]
I'll take a look tonight or tomorrow morning. Sorry that took you so long to modified what I've done...
@arthur-e I think we should remove all the files except the one Meha created. I'm not sure what is the most proper way to do so. Should I delete files on my local computer and commit again?

**Comment by mehajain13** [comment]
Hi @OscarFHC - no problem at all. I thought your lab was great!!! I just wanted to take out the bootstrapping stuff because I felt like that might be too confusing for students and add a bit more on how they can calculate all the outputs they get from a t-test. I feel like sampling distributions and confidence intervals were really confusing for students during my last lecture so I'm hoping this lab will help clear things up.

**Comment by OscarFHC** [comment]
I just went through it and have two following opinions.
1. I anticipate that students would get confused by the function calculating the t statistics, especially the `val <- (samplem - refval)/sem` part. Some students are still not clear about the standard error and standard deviation. 
2. This might not be directly related to the lab. I don't think I did a good job explaining the probability of committing type I and typeII error on Monday. I'm wondering if you want to explain it again in lecture and maybe include a demo in the lab.

**Comment by mehajain13** [comment]
Thanks Oscar! I tried to touch on both of these issues in lecture yesterday so I'm not going to add anything additional to the lab about this. Hope that's okay!

**Comment by arthur-e** [comment]
I prepared an example for my lab today using sunspot data. I plan to go over it in the first 30 minutes of lab, then turn them loose on the assignment.

- The data (basically, daily average sunspot counts) are non-normal so I can help students understand the difference between a single large sample (still not normally distributed) and a large sampling distribution (normal, courtesy of the Central Limit Theorem).
- I show them we can apply descriptive statistics from the normal distribution (a Z-score) if we square-root transform the data to make it more normal, but this is kind of hack. The point is to make a connection, later, between Z-scores and t-statistics.
- We explore a null hypothesis H0: The last solar cycle (2007-2017, inclusive) had a daily mean sunspot number no different from the long-term mean (from our sampling distribution).
- We calculate t-statistics for the last solar cycle (2007-2017) and the Dalton minimum (early 1800s). For the last solar cycle, we fail to reject H0 with a two-tailed test. For the Dalton minimum, we reject H0 (daily mean sunspot activity during the Dalton minimum is not less than the long-term mean) with a one-tailed test.

I'll post the code later to the Week 4 lab folder.

**Comment by mehajain13** [comment]
Sounds good. Thanks, Arthur.

**Comment by arthur-e** [comment]
The file is uploaded; it is called `EAS538_week4_lab_supplemental_SunspotData.R`.

**Comment by OscarFHC** [comment]
hi @mehajain13 and @arthur-e ,

I encountered a question about the following statement in the r script Arthur created.
`# We use the t-distribution for testing differences between means because the
#   *distribution of differences* follows a t-distribution
hist(sunspots.means - mean(sunspots.means))`

I personally agree with the student that by misusing mean would not make the normal distribution into a t-distribution. It's just shifting the distribution along the axis. No matter what, this is not critical here I suppose. I would suggest taking this out for clarity. I'll take that out and re-upload it if you all agree with this.

**Comment by arthur-e** [comment]
That was my understanding as to why we use a t-distribution and the t-test for means testing, although as the degrees of freedom grows large, the t-distribution converges to the normal distribution. To avoid any confusion, I have removed this section from the supplemental material.

**Comment by OscarFHC** [comment]
Thanks, Arthur. This is a great point and makes to think why exactly we should use t-test/t-distribution. Obviously, moving a distribution along the axis does not make the distribution into other distribution. 

My understanding was that t-distribution differs from the normal distribution in its inclusion of extreme values (longer right and left tails), especially when the sample size is small. The reason we use t-distribution is that we want to be safe when sample size might not be large enough since t-distribution will approximate the normal distribution when sample size grows larger. Otherwise, I would always use bootstrap to construct the confidence interval according to a normal distribution. I hope I understand this correctly.

**Comment by arthur-e** [comment]
Hi @OscarFHC, I agree with everything you said, in particular, that the t-distribution has fatter tails to model the influence of extreme values in small samples. However, a t-test only consumes one degree of freedom, so for many (larger) datasets it should actually quite similar to a normal distribution. And yet the t-distribution and t-test are still used. I wonder if it is a matter of "best practices," because when we introduce linear regression we are starting to consume more degrees of freedom, and it's possible that the residual degrees of freedom are small enough that the t-statistic is more reliable.

Anyway, we don't have to hash it out here. There's plenty of other things the students need to comprehend, first. I'll just tell them the t-distribution has critical values and probability values, just like the normal distribution, and we use it for testing differences between means.
