### ISSUE TITLE
Uploaded Week 7 lab

### ISSUE THREAD

**Issue by mehajain13** [OscarFHC/EAS538_2018#28]
Hey @OscarFHC and @arthur-e 

I've uploaded the updated week 7 lab. The main thing I'll need help with is fixing the formatting - right now the text for each section + exercise is smushed all together. Let me know if you also catch any errors.

Thanks and sorry for the extreme delay! I've been drowning these past 2 weeks with job search committees and Ph.D. admissions. I'll get back on top of things soon!

m

**Comment by arthur-e** [comment]
Hi @mehajain13,

Taking a look now--quick question; this week's lab is marked as "week7_8" -- for both weeks 7 and 8???

Arthur

**Comment by mehajain13** [comment]
It should just be week 7. Thanks!!

**Comment by arthur-e** [comment]
My changes:

1. Added examples from Kieran Healy's book on data visualization and Anscombe's quartet to show how different datasets can have the same correlation coefficient, trendline, etc.
2. Broke out Exercise 2 into two parts (plotting first, *then* calculating the correlation coefficient) so that students don't forget to do one or the other.
3. Removed some text outside of Exercises, e.g., "Interpret your results;" students have told me before that they are unsure if they need to answer questions like these as part of the assignment.
4. In Exercise 4, I edited the prompt for clarity. I also asked students to verify that `SSY - SSYp` is equal to `SSE` (this should help them check that they have calculated `SSE` correctly).

Also, I neglected to tell students last week that they **must** start including R code and outputs in their assignments. As we discussed that students should start showing code and since I've added, e.g., "R code and outputs required" to the header of each relevant Exercise, I'm going to stress in class that they will lose points if they fail to do this.

**Comment by arthur-e** [comment]
Also, I moved the `Week7_8_lm` folder to a new folder called `Week7_lm`, assuming we're doing something different next week. Pushing soon!

**Comment by OscarFHC** [comment]
I'll wait take a look after @arthur-e push it. Thanks.

**Comment by mehajain13** [comment]
Thanks to you both! I made some small edits and updated the lab. Hopefully that doesn't mess up any edits either of you may have been doing on your local machine. If it does, please disregard my changes (they aren't big) and just use whatever file you worked on.
