### ISSUE TITLE
Week 12 posted

### ISSUE THREAD

**Issue by mehajain13** [OscarFHC/EAS538_2018#37]
Hey @arthur-e & @OscarFHC 

I posted this week's lab. It's called EAS538_week12_GLM.Rmd

Oscar, I used a lot of what you wrote last year but tried to simplify it a bit.

Thanks!
m

**Comment by arthur-e** [comment]
I just pushed some changes to the "Rationale" section that I felt were important. I am worried that students may get the impression that the GLM is just a simple fix for non-normality, particularly because they are starting to learn that non-normality in residuals is the least important assumption of ordinary least-squares regression. I don't want them to think GLMs are no more important or significant than a log-transformation of the dependent variable. Rather, GLMs are a distinct class of model that may actually fit the data better; that they fundamentally represent the problem under investigation much more accurately than an ordinary least-squares regression. Please check my short example here.

**Comment by mehajain13** [comment]
Thanks @arthur-e!! Your edits look great and I agree are important for students to understand the point of GLMs and when to use them. One quick thing - I thought it was okay to use OLS with count data as long as the count data are normally distributed and have lots of values that essentially make it a continuous dataset. From the wording now it sounds like you should always use Poisson GLM for count data. If you both agree with the possibility of using OLS, it'd be good to make this clear in the rationale section.

**Comment by arthur-e** [comment]
I agree, a large sample of count data could be modeled using OLS but if the mean of the counts is small then there will be some unrealistic, negative predictions and confidence bounds. I've amended the rationale to distinguish this.

**Comment by OscarFHC** [comment]
I just added some words to address 

> - Counts (which can only take on positive integer values) or rates;  
*Note that it is okay to use OLS with count data as long as the count data are normally distributed and have lots of values that are far from 0. Just be aware that, due to the normality assumption of OLS, some non-existing negative values will be counted with OLS method.

**Comment by OscarFHC** [comment]
Never mind I didn't know Arthur was editing it.

**Comment by arthur-e** [comment]
If there are no further changes by 1:00 PM, I'll put it up on Canvas.

**Comment by OscarFHC** [comment]
I'm good with what it is now.
